version: '3.9'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: dannys
      POSTGRES_DB: dannys
      POSTGRES_PASSWORD: dannys
    env_file:
      - ../api/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  fastapi:
    build:
      context: ../api
      dockerfile: ./Dockerfile
    env_file:
      - ../api/.env
    ports:
      - "8000:8000"
    container_name: fastapi-new
    depends_on:
      - db
    command: ["/opt/api/docker-entrypoint.sh"]
    volumes:
      - ../api:/opt/api

  vue:
    build:
      context: ../client
      dockerfile: ./Dockerfile
    volumes:
      - '.:/opt/client'
      - '/opt/client/node_modules'
    ports:
      - '8080:8080'

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "5370:5370"

volumes:
  postgres_data: { }
  redis_data: { }