version: '3.9'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: dannys
      POSTGRES_DB: dannys
      POSTGRES_PASSWORD: dannys
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:  
      - postgres_data:/var/lib/postgresql/data/
      
  fastapi:
    build: 
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    container_name: fastapi
    depends_on:
      - db
    command: ["/opt/api/docker-entrypoint.sh"]
    volumes:
      - .:/opt/api

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "8880:80"

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    ports:
      - "5370:5370"

volumes:
  postgres_data: { }
  redis_data: { }